version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: php:fpm-php8.0
    container_name: play-lumen-dice-api
    restart: unless-stopped
    tty: true
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:1.21.1
    container_name: play-lumen-dice-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
