// Config request
@hostname = localhost
@port_debug = 9003
@port_deault = 1080
@port_local = 8000
@host = {{hostname}}:{{port_local}}
@contentType = application/json
// application/json|image/png
@accept = image/png

// Parans
@quantity = 5
@face = 6

GET http://{{host}}/api/dice/play?quantity={{quantity}}&face={{face}} HTTP/1.1
content-type: {{contentType}}
Accept: {{accept}}
###
